FROM ubuntu:latest
MAINTAINER jj
RUN DBEIAN_FRONTEND=noninteractive apt-get update && \
   apt-get install python python-pip python-mysql.connector -y && \
   apt-get clean autoclean && \
   apt-get autoremove && \
   rm -rf /var/lib/{apt,dpkg,cache,log}
VOLUME /results/
RUN mkdir /app/
ADD . /app/
RUN pip install -r /app/requirements.txt && chmod +x /app/test.py
WORKDIR /results/
CMD sleep 10 && \
    /app/test.py dummy 10 1000 && \
    /app/test.py neo 10 1000 &&  \
    /app/test.py mongo 10 1000 && \
    /app/test.py sql 10 1000
